---
title: Trazabilidad de datos TFM (flujo de datasets; valor = nº de campos compartidos)
---
sankey-beta

expedientes,df_alumno_base,15
df_alumno_base,df_alumno,32
df_alumno,df_alumno_limpio,34
df_alumno_limpio,df_expediente_base,21
df_expediente_base,df_expediente_features,41
df_expediente_features,df_exp_automl_target,49
df_exp_automl_target,dataset_final_tfm,23
dataset_final_tfm,X_train,24
X_train,X_train_prep,28
df_expediente_features,df_exp_target_eda,49
df_exp_automl_target,df_eda_final,24
df_eda_final,df_eda_perfiles,26
X_test,meta_test_app,28
dataset_final_tfm,X_test,24
