# -*- coding: utf-8 -*-
"""Genera el Excel inventario de notebooks (trazabilidad). SOLO LECTURA del repo:
solo escribe en la carpeta _trazabilidad_notebooks/. Datos basados en la lectura
de los .ipynb (no se inventan valores)."""
from pathlib import Path
import pandas as pd

# columnas: notebook, fase, que_hace, entradas, salidas, uso
ROWS = [
    # ---------------- FASE 0 ----------------
    ("00_configuracion_proyecto", "fase0",
     "Configura entorno, verifica los 2 Excel originales y genera index.html principal.",
     "data/00_raw/datos_proyecto_sin_preinscrip.xlsx; data/00_raw/preinscripcion_si.xlsx",
     "docs/html/index.html; docs/html/fase7/fase7_index.html",
     "Arranque de Fase 0: valida prerrequisitos de datos y publica portada del proyecto."),
    ("f0_actualizar_resumen", "fase0",
     "Regenera index.html y resumen del orquestador leyendo el estado del disco (sin ejecutar fases).",
     "Excel originales; parquets; data/06_evaluacion/metricas_modelo.json (lectura dinamica) (verificar)",
     "docs/html/index.html; docs/html/orquestador_resumen.html",
     "Refresca la web tras correcciones, sin reejecutar el pipeline."),
    ("f0_generar_excel_prueba", "fase0",
     "Crea versiones DEMO reducidas (~50 alumnos) de los 2 Excel originales.",
     "data/00_raw/datos_proyecto_sin_preinscrip.xlsx; data/00_raw/preinscripcion_si.xlsx",
     "data/00_raw/ejemplo/datos_proyecto_sin_preinscrip_DEMO.xlsx; data/00_raw/ejemplo/preinscripcion_si_DEMO.xlsx",
     "Genera datos de prueba ficticios para el modo DEMO."),
    ("f0_setup_demo", "fase0",
     "Descomprime el ZIP DEMO y copia los 2 Excel reducidos a data/00_raw/ (con backup previo).",
     "data/demo/demo_excel.zip",
     "data/00_raw/datos_proyecto_sin_preinscrip.xlsx; data/00_raw/preinscripcion_si.xlsx; backups _BACKUP_<fecha>.xlsx",
     "Instala los datos DEMO en data/00_raw/ para ejecutar el pipeline en modo demostracion."),
    ("f0_validar_excel", "fase0",
     "Validacion profunda de los Excel originales contra el contrato src/validacion/contrato_excel.py.",
     "data/00_raw/datos_proyecto_sin_preinscrip.xlsx; data/00_raw/preinscripcion_si.xlsx (verificar variable)",
     "(ninguna) - imprime resultados de validacion",
     "Comprueba estructura, columnas, tipos y cruces de IDs antes de la Fase 1."),
    ("orquestador_maestro", "fase0",
     "Orquestador maestro: ejecuta en cadena los orquestadores de cada fase (F1-F6) y genera resumen HTML.",
     "notebooks/faseX/fX_m00_ejecucion.ipynb (verificar)",
     "docs/html/orquestador_resumen.html (+ salidas de los notebooks ejecutados)",
     "Lanza el pipeline completo del proyecto y publica resumen dinamico."),

    # ---------------- FASE 1 ----------------
    ("f1_m00_ejecucion", "fase1",
     "Orquestador de Fase 1; ejecuta los notebooks en secuencia (nbconvert) y genera HTML de estado.",
     "los 12 notebooks de notebooks/fase1_transformacion/",
     "docs/html/fase1/m00_ejecucion.html",
     "Punto de entrada que lanza el pipeline de transformacion y reporta progreso."),
    ("f1_m00_indice", "fase1",
     "Genera la pagina indice HTML de Fase 1 con lista de modulos y KPIs.",
     "Excel originales; data/02_processed/df_alumno.parquet",
     "docs/html/fase1/fase1_index.html",
     "Portada de navegacion; se ejecuta al final porque necesita los parquets."),
    ("f1_m01_reportes_raw", "fase1",
     "Genera reportes Sweetviz de los datos ANTES de limpiar (datos originales).",
     "data/00_raw/*.xlsx (por hojas)",
     "docs/html/fase1/reportes_raw/reporte_*.html; docs/html/fase1/m01_reportes_raw.html",
     "EDA inicial sobre datos originales previo a la limpieza."),
    ("f1_m02_limpieza", "fase1",
     "Limpia y estandariza las 9 tablas de datos originales (nombres, vacios, tipos).",
     "data/00_raw/*.xlsx (por hojas)",
     "data/01_interim/<tabla>.parquet (una por tabla, incl. preinscripcion.parquet); docs/html/fase1/m02_limpieza.html",
     "Nucleo de la limpieza; produce los parquets intermedios de la fase."),
    ("f1_m03_reportes_clean", "fase1",
     "Genera reportes Sweetviz de los datos DESPUES de limpiar para comparar con los originales.",
     "data/01_interim/*.parquet",
     "docs/html/fase1/reportes_clean/reporte_*.html; docs/html/fase1/m03_reportes_clean.html",
     "Validacion de la limpieza frente a M01."),
    ("f1_m04_dataset_final", "fase1",
     "Orquestador que lanza M04a->M04d en secuencia para construir el dataset final.",
     "notebooks f1_m04a/b/c/d (via %run)",
     "docs/html/fase1/m04_dataset_final.html (+ actualiza index)",
     "Coordina la construccion del dataset de alumnos con todas las correcciones."),
    ("f1_m04a_union_tablas", "fase1",
     "Une los parquets por tabla (interim) en un unico dataframe a nivel de expediente.",
     "data/01_interim/*.parquet (8 tablas del Excel principal)",
     "data/02_processed/df_alumno_base.parquet",
     "Primer paso de M04: integra tablas en un dataframe base."),
    ("f1_m04b_union_preinscripcion", "fase1",
     "Completa df_alumno.parquet uniendo la preinscripcion al df_alumno_base.",
     "data/02_processed/df_alumno_base.parquet; data/01_interim/preinscripcion.parquet",
     "data/02_processed/df_alumno.parquet; data/02_processed/df_alumno.csv; HTML M04b (verificar nombre)",
     "Anade preinscripcion y crea el dataset final inicial df_alumno."),
    ("f1_m04c_correccion_notas", "fase1",
     "Corrige valores incorrectos de nota_acceso cruzando con la preinscripcion.",
     "data/02_processed/df_alumno.parquet; data/01_interim/preinscripcion.parquet",
     "data/02_processed/df_alumno.parquet; data/02_processed/df_alumno.csv",
     "Correccion de nota_acceso (sobrescribe df_alumno)."),
    ("f1_m04d_correccion_via_acceso", "fase1",
     "Corrige y estandariza los valores de via_acceso en el dataset de alumnos.",
     "data/02_processed/df_alumno.parquet",
     "data/02_processed/df_alumno.parquet; data/02_processed/df_alumno.csv",
     "Ultima correccion de M04; deja df_alumno listo como dataset final de la fase."),
    ("f1_m05_dashboard", "fase1",
     "Genera un dashboard HTML resumen con metricas clave de la transformacion.",
     "metricas de la fase (no se observan read_* explicitos) (verificar)",
     "docs/html/fase1/m05_dashboard.html",
     "Panel resumen visual de registros procesados, tablas unidas y correcciones."),
    ("f1_m05_m06_trazabilidad", "fase1",
     "Genera grafos de trazabilidad (estatico, D3.js y Pyvis) del flujo tablas->df_alumno.",
     "data/01_interim/*.parquet; data/02_processed/df_alumno.parquet",
     "docs/html/fase1/trazabilidad_fase1.png; docs/html/fase1/trazabilidad_fase1.jpg; docs/html/fase1/m05_grafo_d3.html; docs/html/fase1/m06_grafo_pyvis.html",
     "Documentacion visual del linaje de datos de la fase (version combinada)."),
    ("f1_m06_grafo", "fase1",
     "Genera grafo interactivo (networkx/SVG) de trazabilidad entre tablas y dataset final.",
     "data/01_interim/*.parquet; data/02_processed/df_alumno.parquet",
     "docs/html/fase1/m06_grafo.html",
     "Trazabilidad visual del pipeline en formato grafo embebido."),
    ("f1_m06_grafo_pyvis", "fase1",
     "Genera grafos de trazabilidad interactivos con Pyvis (+ matplotlib estatico).",
     "data/01_interim/*.parquet; data/02_processed/df_alumno.parquet",
     "docs/html/fase1/trazabilidad_fase1.png; docs/html/fase1/trazabilidad_fase1.jpg; docs/html/fase1/m05_grafo_d3.html; docs/html/fase1/m06_grafo_pyvis.html",
     "Version Pyvis de la trazabilidad; alternativa interactiva a m06_grafo."),

    # ---------------- FASE 2 ----------------
    ("f2_m00_ejecucion", "fase2",
     "Orquesta la ejecucion secuencial de todos los notebooks de Fase 2 y genera su HTML.",
     "notebooks de fase2 (m00_indice, m01-m07)",
     "docs/html/fase2/m00_ejecucion.html",
     "Punto de entrada: lanza en orden todos los modulos EDA."),
    ("f2_m00_indice", "fase2",
     "Genera la pagina indice de Fase 2 con KPIs globales del dataset.",
     "data/02_processed/df_alumno.parquet",
     "docs/html/fase2/m00_indice.html",
     "Portada/indice de navegacion con metricas resumen."),
    ("f2_m01_inspeccion", "fase2",
     "Inspeccion inicial del dataset (tipos, nulos, cardinalidad, unicos).",
     "data/02_processed/df_alumno.parquet",
     "docs/html/fase2/m01_inspeccion.html (+ graficos m01_*.html)",
     "Primera caracterizacion estructural de las variables."),
    ("f2_m02_calidad", "fase2",
     "Analisis de calidad de datos (cursos, filas/alumno, titulaciones, rama, sexo, anomalias).",
     "data/02_processed/df_alumno.parquet",
     "docs/html/fase2/m02_calidad.html (+ graficos m02_*.html)",
     "Evalua consistencia/anomalias de dimensiones clave."),
    ("f2_m03_nulos", "fase2",
     "Analisis y clasificacion de valores nulos (patron, barras, correlacion).",
     "data/02_processed/df_alumno.parquet",
     "docs/html/fase2/m03_nulos.html (+ graficos m03_*.html)",
     "Diagnostico de ausencias para decidir imputacion."),
    ("f2_m04_univariante_num", "fase2",
     "Analisis univariante de variables numericas (boxplots, histogramas, QQ, violin).",
     "data/02_processed/df_alumno.parquet",
     "docs/html/fase2/m04_univariante_num.html (+ graficos m04_*.html)",
     "Caracteriza distribucion, outliers y forma de numericas."),
    ("f2_m05_univariante_cat", "fase2",
     "Analisis univariante de variables categoricas (cardinalidad, paises, provincias, top-N).",
     "data/02_processed/df_alumno.parquet",
     "docs/html/fase2/m05_univariante_cat.html (+ graficos m05_*.html)",
     "Describe distribucion de categoricas y su cardinalidad."),
    ("f2_m06_evolucion", "fase2",
     "Analisis de evolucion temporal por curso (matriculas, notas, egresados, becas, creditos).",
     "data/02_processed/df_alumno.parquet",
     "docs/html/fase2/m06_evolucion.html (+ graficos m06_*.html)",
     "Muestra tendencias longitudinales del alumnado."),
    ("f2_m06b_temporal", "fase2",
     "Complementa M06 con tres visualizaciones temporales adicionales (Altair).",
     "data/02_processed/df_alumno.parquet",
     "docs/html/fase2/m06_temporal.html",
     "Refuerza el analisis temporal con vistas Altair."),
    ("f2_m07_conclusiones", "fase2",
     "Resume conclusiones de Fase 2 y dibuja el flujo/estado del proyecto.",
     "data/02_processed/df_alumno.parquet; data/06_evaluacion/metricas_modelo.json (n_features)",
     "docs/html/fase2/m07_conclusiones.html (+ m07_flujo_proyecto.html)",
     "Cierre de la fase EDA con sintesis y diagrama de flujo."),

    # ---------------- FASE 3 ----------------
    ("f3_m00_ejecucion", "fase3",
     "Orquestador de Fase 3; ejecuta cada notebook en secuencia (nbconvert) con tabla de progreso.",
     "los notebooks de fase3_features",
     "docs/html/fase3/m00_ejecucion.html",
     "Punto de entrada que lanza la fase de features encadenada."),
    ("f3_m00_indice", "fase3",
     "Genera la pagina indice HTML de Fase 3; lee 2 parquet solo para KPIs.",
     "data/03_features/df_expediente_features.parquet; data/automl/dataset_final_tfm.parquet",
     "docs/html/fase3/fase3_index.html",
     "Navegacion/indice web de la Fase 3."),
    ("f3_m01_validacion", "fase3",
     "Valida y limpia el dataset procesado (duplicados, tipos, anomalias).",
     "data/02_processed/df_alumno.parquet",
     "data/03_features/df_alumno_limpio.parquet; data/03_features/df_longitudinal_trayectoria.parquet; HTML",
     "Limpieza inicial; produce el dataset limpio que consume la agregacion."),
    ("f3_m02_agregacion", "fase3",
     "Agrega a nivel de expediente academico calculando variables de trayectoria.",
     "data/03_features/df_alumno_limpio.parquet",
     "data/03_features/df_expediente_base.parquet; HTML",
     "Pasa de filas por matricula a una fila por expediente; base de las features."),
    ("f3_m03_features", "fase3",
     "Genera features temporales y derivadas a partir del expediente base.",
     "data/03_features/df_expediente_base.parquet; data/03_features/df_alumno_limpio.parquet",
     "data/03_features/df_expediente_features.parquet (+ .csv); HTML",
     "Dataset con todas las features; base de los encodings M04a/M04b."),
    ("f3_m04_index", "fase3",
     "Pagina indice de los 2 notebooks de encoding (M04a numerico, M04b mixto).",
     "data/03_features/df_exp_automl_target.parquet; data/03_features/df_exp_target_eda.parquet",
     "docs/html/fase3/m04_encoding.html",
     "Indice/navegacion del bloque de encoding."),
    ("f3_m04a_automl_target", "fase3",
     "Aplica encoding 100% numerico (ordinal) para AutoML (AutoGluon, PyCaret, H2O).",
     "data/03_features/df_expediente_features.parquet",
     "data/03_features/df_exp_automl_target.parquet; HTML",
     "Prepara el dataset numerico para los motores AutoML."),
    ("f3_m04b_eda_target", "fase3",
     "Aplica encoding mixto (numerico + strings legibles) para graficos interpretables del EDA.",
     "data/03_features/df_expediente_features.parquet",
     "data/03_features/df_exp_target_eda.parquet; HTML",
     "Prepara el dataset interpretable para EDA."),
    ("f3_m05_target_export", "fase3",
     "Define el target abandono, target encoding a titulacion, elimina leakage y exporta D y D_strict.",
     "data/03_features/df_exp_automl_target.parquet; data/03_features/df_exp_target_eda.parquet",
     "data/automl/dataset_final_tfm.parquet (D_strict); data/automl/df_exp_automl_D.parquet (D); data/03_features/df_eda_con_target.parquet; HTML",
     "PUENTE: produce los datasets finales con target para AutoML y modelado."),
    ("f3_m06_alerta_temprana", "fase3",
     "Baselines rapidos (XGBoost) sobre D y D_strict para validar ausencia de leakage.",
     "data/automl/df_exp_automl_D.parquet; data/automl/dataset_final_tfm.parquet",
     "data/automl/quick_baseline_casoD.parquet; data/automl/quick_baseline_casoD.xlsx (hojas 'todos' + por caso); data/automl/feature_importance_caso{caso}.png; HTML",
     "Chequeo temprano de calidad/leakage de los datasets D."),
    ("f3_m07_validacion", "fase3",
     "Valida D y D_strict con baselines, estabilidad por semillas y feature importance.",
     "data/automl/dataset_final_tfm.parquet; data/automl/df_exp_automl_{caso}.parquet",
     "data/03_features/validacion/*.png/.xlsx; HTML",
     "Validacion exhaustiva (estabilidad y baselines) de los datasets finales."),
    ("f3_m08_auditoria", "fase3",
     "Auditoria final de features (constantes, leakage), regenera D_strict (27->24 cols) y construye df_eda_final.",
     "data/automl/df_exp_automl_D.parquet; data/automl/dataset_final_tfm.parquet; data/03_features/df_eda_con_target.parquet; data/03_features/df_expediente_base.parquet",
     "data/automl/df_exp_automl_{caso}.{parquet,csv,xlsx,json}; diccionario_columnas.json; auditoria_features_D_strict.xlsx; data/04_eda/df_eda_final.{parquet,csv,xlsx,json}; HTML",
     "PUENTE: auditoria y consolidacion final de datasets de modelado y del df_eda_final."),
    ("f3_m09_perfiles_riesgo", "fase3",
     "Construye perfiles de riesgo de abandono (alto/medio/bajo) por rama, via, beca y preferencia.",
     "data/04_eda/df_eda_final.parquet",
     "data/04_eda/df_eda_perfiles.parquet; HTML",
     "Analisis de perfiles de riesgo sobre el df_eda_final."),
    ("plantilla_fX_m0Y", "fase3",
     "Plantilla base para crear nuevos notebooks de fase/modulo (sin logica real).",
     "(ninguna)",
     "RUTA_FASEX/m0Y_nombre.html (placeholder)",
     "Andamiaje reutilizable para nuevos modulos. HUERFANO (utilidad)."),

    # ---------------- FASE 4 ----------------
    ("f4_m00_ejecucion", "fase4",
     "Orquestador de Fase 4; ejecuta los 10 notebooks (nbconvert) y genera HTML resumen.",
     "notebooks/fase4_eda/*.ipynb",
     "docs/html/fase4/m00_ejecucion.html",
     "Punto de lanzamiento de la fase EDA; coordina y reporta."),
    ("f4_m00_indice", "fase4",
     "Indice/portada de Fase 4; carga el dataset EDA para metadatos y enlaza modulos.",
     "data/04_eda/df_eda_final.parquet",
     "docs/html/fase4/ (HTML indice) (verificar nombre)",
     "Pagina de navegacion inicial de la fase EDA."),
    ("f4_m01_inspeccion", "fase4",
     "Inspeccion general del dataset EDA (estructura, tipos, nulos, dimensiones).",
     "data/04_eda/df_eda_final.parquet",
     "docs/html/fase4/m01_inspeccion.html",
     "Primera revision de calidad/forma de los datos."),
    ("f4_m02_target", "fase4",
     "Analisis de la variable objetivo (target) sobre el dataset EDA.",
     "data/04_eda/df_eda_final.parquet",
     "docs/html/fase4/m02_target.html",
     "Caracteriza distribucion/balance del target."),
    ("f4_m03_distribuciones_num", "fase4",
     "Estudio de distribuciones de variables numericas (figuras PNG embebidas).",
     "data/04_eda/df_eda_final.parquet",
     "docs/html/fase4/m03_distribuciones_num.html",
     "EDA univariante numerico."),
    ("f4_m04_distribuciones_cat", "fase4",
     "Estudio de distribuciones de variables categoricas y nulos.",
     "data/04_eda/df_eda_final.parquet",
     "docs/html/fase4/m04_distribuciones_cat.html",
     "EDA univariante categorico."),
    ("f4_m05_bivariante", "fase4",
     "Analisis bivariante (num y cat frente al target); tablas y figuras.",
     "data/04_eda/df_eda_final.parquet",
     "data/03_features/resultados_bivariante_numericas.csv; resultados_bivariante_categoricas.csv; PNGs; HTML",
     "Mide relacion de cada variable con el target; alimenta seleccion de features."),
    ("f4_m06_correlaciones", "fase4",
     "Analisis de correlaciones; exporta la tabla de correlaciones (principal y copia).",
     "data/04_eda/df_eda_final.parquet",
     "data/03_features/f4_m06_correlaciones_tabla.parquet; data/04_eda/f4_m06_correlaciones_tabla.parquet; HTML",
     "Detecta redundancia/multicolinealidad para reducir features."),
    ("f4_m07_seleccion_features", "fase4",
     "Seleccion de features combinando ranking previo (m06) e importancias AutoML.",
     "data/03_features/<ranking> (fallback df_eda_final); data/automl/automl_top_modelos.parquet (opcional)",
     "data/03_features/f4_m07_features_seleccionadas.parquet (+ .csv); HTML",
     "Produce la lista definitiva de variables candidatas al modelado."),
    ("f4_m08_perfiles_riesgo", "fase4",
     "Construccion de perfiles de riesgo a partir del dataset EDA y la tabla de correlaciones.",
     "data/04_eda/df_eda_final.parquet; data/03_features/f4_m06_correlaciones_tabla.parquet",
     "docs/html/fase4/m08_perfiles_riesgo.html (verificar)",
     "Segmenta/caracteriza perfiles de estudiantado segun riesgo."),
    ("f4_m09_conclusiones_eda", "fase4",
     "Conclusiones del EDA; consolida ranking de features y guarda ranking final.",
     "data/automl/dataset_final_tfm.parquet; data/automl/<ranking> (fallback feature_ranking_m06.parquet)",
     "data/automl/ranking_final_fase4.parquet; HTML",
     "Cierre del EDA; deja preparado el ranking final para AutoML/modelado."),

    # ---------------- FASE AUTOML ----------------
    ("fautoml_m00_ejecucion", "fase_automl",
     "Orquestador que ejecuta M01-M07 + M00_indice (nbconvert). M06 comentado por coste (~7,3h).",
     "notebooks fautoml_m01..m07 + m00_indice",
     "docs/html/fase_automl/m00_ejecucion.html",
     "Punto de entrada de la fase AutoML; genera HTML resumen de estado."),
    ("fautoml_m00_indice", "fase_automl",
     "Genera la pagina indice HTML de AutoML con resumen del dataset y top de modelos.",
     "data/automl/dataset_final_tfm.parquet; data/automl/automl_top_modelos.parquet",
     "docs/html/fase_automl/ (HTML) (verificar nombre)",
     "Portada/indice; se ejecuta al final porque necesita el top de M07."),
    ("fautoml_m01_baselines", "fase_automl",
     "Entrena baselines de scikit-learn con hiperparametros por defecto.",
     "data/automl/dataset_final_tfm.parquet",
     "data/automl/results_baselines.parquet; HTML",
     "Linea base de referencia (6 modelos) para comparar contra AutoML."),
    ("fautoml_m02_lazypredict", "fase_automl",
     "Evalua ~27 modelos rapidamente con LazyPredict.",
     "data/automl/dataset_final_tfm.parquet; data/automl/results_baselines.parquet (opcional)",
     "data/automl/results_lazypredict.parquet; HTML",
     "Cribado amplio de algoritmos; entorno env_lazypredict."),
    ("fautoml_m03_pycaret", "fase_automl",
     "Compara ~15 modelos con PyCaret (CV=5) y guarda el mejor modelo.",
     "data/automl/dataset_final_tfm.parquet; results_baselines/lazypredict.parquet (opcional)",
     "data/automl/results_pycaret.parquet; data/automl/mejor_modelo_pycaret.pkl; HTML",
     "Framework AutoML con CV y persistencia del mejor; entorno env_pycaret."),
    ("fautoml_m04_h2o", "fase_automl",
     "Ejecuta H2O AutoML (~22 modelos).",
     "data/automl/dataset_final_tfm.parquet; results_*.parquet previos (opcional)",
     "data/automl/results_h2o.parquet; HTML",
     "Framework AutoML basado en Java; entorno env_h2o."),
    ("fautoml_m05_autogluon", "fase_automl",
     "Ejecuta AutoGluon (~16 modelos).",
     "data/automl/dataset_final_tfm.parquet; results_*.parquet previos (opcional)",
     "data/automl/results_autogluon.parquet; HTML",
     "Framework AutoML por ensamblado/stacking; entorno env_autogluon."),
    ("fautoml_m06_tabpfn", "fase_automl",
     "Evalua TabPFN v2 (transformer preentrenado) sobre el dataset completo.",
     "data/automl/dataset_final_tfm.parquet; results_*.parquet previos (opcional)",
     "data/automl/results_tabpfn.parquet; HTML",
     "Modelo fundacional tabular; muy costoso (~7,3h), se ejecuta aparte; entorno tfm_abandono."),
    ("fautoml_m07_comparativa", "fase_automl",
     "Consolida todos los results_*.parquet (M01-M06) en ranking global por F1 e identifica mejor por framework.",
     "data/automl/results_{baselines,lazypredict,pycaret,h2o,autogluon,tabpfn}.parquet",
     "data/automl/automl_comparativa_final.xlsx; data/automl/automl_top_modelos.parquet; automl_comparativa_final.json; HTML (+ PNGs)",
     "PUENTE: sintesis final de la fase; produce el ranking que consume el indice M00 y Fase 4."),
    ("fautoml_setup_entornos", "fase_automl",
     "Crea (una sola vez) los entornos conda aislados por framework via subprocess/conda.",
     "(ninguna)",
     "(ninguna) - crea entornos conda y kernels Jupyter",
     "Preparacion del entorno antes de M02-M05. HUERFANO (setup)."),
    ("ver_entornos", "fase_automl",
     "Lee metadatos de M02-M05 y muestra el kernel Jupyter asignado a cada uno.",
     "notebooks fautoml_m02..m05.ipynb (json.load)",
     "(ninguna) - imprime",
     "Diagnostico de kernel/entorno por notebook. HUERFANO (utilidad)."),
    ("comproba_parquet_2", "fase_automl",
     "Busca el parquet de target AutoML en varias rutas e inspecciona shape/columnas/tipos.",
     "data/05_automl/, data/04_features/, data/automl/ df_exp_automl_target(_final).parquet",
     "(ninguna) - imprime",
     "Comprobacion previa para localizar/validar el dataset de entrada. HUERFANO (utilidad)."),
    ("comprobar_existe_parquet", "fase_automl",
     "Verifica existencia y caracteristicas de varios parquets (AutoML, EDA, features).",
     "data/automl/*.parquet; data/03_features/*.parquet; data/04_eda/*.parquet",
     "(ninguna) - imprime",
     "Diagnostico de disponibilidad de datos. HUERFANO (utilidad)."),

    # ---------------- FASE 5 ----------------
    ("f5_m00_ejecucion", "fase5",
     "Orquesta la ejecucion secuencial de todos los notebooks de Fase 5 (nbconvert) con progreso.",
     "notebooks/fase5_modelado/*.ipynb; src/utils/orquestador.py",
     "HTML de pagina (render_pagina)",
     "Orquestador de la fase; reejecuta el pipeline de modelado en bloque."),
    ("f5_m00_indice", "fase5",
     "Pagina indice de Fase 5; lee el dataset de modelado para mostrar dimensiones.",
     "data/03_features/dataset_final_tfm.parquet (verificar ruta vs data/automl/)",
     "HTML indice (render_pagina_desde_fichero)",
     "Portada/navegacion de la fase de modelado."),
    ("f5_m01_maestro", "fase5",
     "Notebook maestro/coordinador de los lineales o de la fase (sin E/S directa detectada).",
     "(verificar)",
     "HTML (render_pagina)",
     "Documentacion/coordinacion de los submodulos lineales m01x. (verificar)"),
    ("f5_m01a_preparacion", "fase5",
     "Audita el dataset, hace split train/test, ajusta el pipeline de preprocesamiento y serializa todo.",
     "data/03_features/dataset_final_tfm.parquet (D_strict) (verificar ruta vs data/automl/)",
     "data/05_modelado/{X_train,X_test,y_train,y_test}.parquet; X_train_prep.parquet; X_test_prep.parquet; pipeline_preprocesamiento.pkl; meta_preparacion.json; HTML",
     "PUENTE interno: genera los datos preparados y el preprocesador que consumen todos los modelos."),
    ("f5_m01b_lineales_basico", "fase5",
     "Entrena lineales basicos (p.ej. LogisticRegression) con 3 estrategias de balanceo.",
     "data/05_modelado/{X,y}_*.parquet; pipeline_preprocesamiento.pkl; X_*_prep.parquet",
     "data/05_modelado/models/*.pkl (12); results/results_lineales_basico.parquet (+ .xlsx/.json); HTML",
     "Bloque basico de la familia lineal del benchmark."),
    ("f5_m01c_lineales_ext", "fase5",
     "Entrena lineales extendidos (Perceptron, SGD, SGDElasticNet) con 3 estrategias.",
     "data/05_modelado/{X,y}_*.parquet; pipeline_preprocesamiento.pkl; X_*_prep.parquet",
     "data/05_modelado/models/*.pkl (9); results/results_lineales_ext.parquet (+ .xlsx/.json); HTML",
     "Bloque extendido de la familia lineal."),
    ("f5_m01d_lineales", "fase5",
     "Unifica los resultados de lineales basicos y extendidos en una tabla completa.",
     "results/results_lineales_basico.parquet; results/results_lineales_ext.parquet",
     "results/results_lineales_completo.parquet (+ .xlsx); HTML",
     "Consolida la familia lineal para el maestro de comparacion."),
    ("f5_m02_arboles", "fase5",
     "Entrena arboles (DecisionTree, RandomForest, ExtraTrees) con 3 estrategias y Optuna.",
     "data/05_modelado/{X,y}_*.parquet; pipeline_preprocesamiento.pkl; X_*_prep.parquet",
     "data/05_modelado/models/*.pkl (9); results/results_arboles.parquet (+ .xlsx/.json); HTML",
     "Familia de arboles del benchmark."),
    ("f5_m03_boosting", "fase5",
     "Entrena gradient boosting (XGBoost, LightGBM, CatBoost...) con 3 estrategias y Optuna.",
     "data/05_modelado/{X,y}_*.parquet; pipeline_preprocesamiento.pkl; X_*_prep.parquet",
     "data/05_modelado/models/*.pkl (12, incl. LightGBM__none.pkl); results/results_boosting.parquet (+ .xlsx/.json); HTML",
     "Familia de boosting; produce el modelo ganador LightGBM y candidatos del top-3."),
    ("f5_m04_otros", "fase5",
     "Entrena 'otros' algoritmos (3 modelos x 3 estrategias) con Optuna.",
     "data/05_modelado/{X,y}_*.parquet; pipeline_preprocesamiento.pkl; X_*_prep.parquet",
     "data/05_modelado/models/*.pkl (9); results/results_otros.parquet (+ .xlsx/.json); HTML",
     "Familia 'otros' del benchmark."),
    ("f5_m05_mlp_ebm", "fase5",
     "Entrena MLP y EBM (3 estrategias cada uno).",
     "data/05_modelado/{X,y}_*.parquet; pipeline_preprocesamiento.pkl; X_*_prep.parquet",
     "data/05_modelado/models/MLP__*.pkl y EBM__*.pkl (6); results/results_mlp_ebm.parquet (+ .xlsx/.json); HTML",
     "Familia de redes neuronales/modelos interpretables."),
    ("f5_m06_ensambles", "fase5",
     "Construye ensambles (Voting, Stacking, Bagging, AdaBoost) cargando modelos base.",
     "data/05_modelado/{X,y}_*.parquet; pipeline_preprocesamiento.pkl; modelos base .pkl",
     "data/05_modelado/models/{Voting,Stacking,Bagging,AdaBoost}__*.pkl (12); results/results_ensambles.parquet (+ .xlsx/.json); HTML",
     "Familia de ensambles; genera Stacking__balanced.pkl usado luego en Wilcoxon."),
    ("f5_m07_comparacion", "fase5",
     "Une los 6 parquets de resultados por familia en la tabla maestra y selecciona top-3 para Fase 6.",
     "results/results_{lineales_completo,arboles,boosting,otros,mlp_ebm,ensambles}.parquet",
     "results/resultados_maestro.parquet (+ .xlsx/.json); top3_fase6.json; HTML",
     "PUENTE: comparacion global del benchmark; decide los modelos que pasan a Fase 6."),
    ("f5_wilcoxon_top3", "fase5",
     "Test de Wilcoxon pareado (AUC y F1 sobre folds CV) entre los 3 mejores modelos.",
     "data/05_modelado/models/{XGBoost__none,LightGBM__none,Stacking__balanced}.pkl; X_train.parquet; y_train.parquet",
     "data/05_modelado/results/wilcoxon_top3.json",
     "Contraste estadistico de significancia entre los candidatos finales."),
    ("f5_wilcoxon_xgb_vs_lgb", "fase5",
     "Test de Wilcoxon pareado (AUC y F1) entre XGBoost y LightGBM.",
     "data/05_modelado/models/{XGBoost__none,LightGBM__none}.pkl; X_train.parquet; y_train.parquet",
     "data/05_modelado/results/wilcoxon_xgb_vs_lgb.json",
     "Comparacion estadistica directa para justificar la eleccion de LightGBM."),
    ("columnas_parquet", "fase5",
     "Utilidad: recorre los parquet de resultados e imprime sus dimensiones.",
     "data/05_modelado/results/*.parquet",
     "(ninguna)",
     "Comprobacion de consistencia de los parquet. HUERFANO (utilidad)."),

    # ---------------- FASE 6 ----------------
    ("f6_m00_ejecucion", "fase6",
     "Orquestador que lanza todos los submodulos de Fase 6 con progreso y genera su HTML.",
     "los demas notebooks (verificar); no lee datos directamente",
     "docs/html/fase6/m00_ejecucion.html",
     "Punto de entrada para ejecutar la fase completa secuencialmente."),
    ("f6_m00_indice", "fase6",
     "Genera la pagina indice HTML de Fase 6 con tabla de modulos y cartel del ganador.",
     "data/06_evaluacion/metricas_modelo.json",
     "docs/html/fase6/fase6_index.html",
     "Navegacion e indice; lee el ganador del JSON (no hardcodeado)."),
    ("f6_m00_preparacion", "fase6",
     "Carga datos/modelo ganador, calcula metricas y genera meta_test.parquet y metricas_modelo.json.",
     "df_eda_final.parquet; data/05_modelado/X_test_prep.parquet; df_exp_automl_target.parquet; df_alumno_limpio.parquet; y_test.parquet; resultados_maestro.parquet; models/LightGBM__none.pkl",
     "data/06_evaluacion/meta_test.parquet; data/06_evaluacion/x_test_ids.parquet; data/06_evaluacion/metricas_modelo.json; HTML",
     "PUENTE: produce el JSON canonico (fuente unica de verdad) y metadatos de test."),
    ("f6_m00b_preparacion_app", "fase6",
     "Construye meta_test_app.parquet fusionando metadatos, features originales y flags _missing.",
     "data/06_evaluacion/meta_test.parquet; data/05_modelado/X_test_prep.parquet; data/05_modelado/X_test.parquet",
     "data/06_evaluacion/meta_test_app.parquet",
     "PUENTE a la app: fichero unico enriquecido para evitar joins en runtime."),
    ("f6_m00c_export_probs", "fase6",
     "Calcula probabilidades del ganador sobre test, las anade a meta_test_app y registra huella en el JSON.",
     "data/06_evaluacion/metricas_modelo.json; meta_test_app.parquet; X_test_prep.parquet; models/<ganador>.pkl",
     "data/06_evaluacion/meta_test_app.parquet (sobrescribe); metricas_modelo.json (probs_modelo_pkl, fecha)",
     "PUENTE a la app: exporta probabilidades precalculadas y deja trazabilidad."),
    ("f6_m01_shap_indice", "fase6",
     "Genera la pagina indice HTML del grupo M01 (SHAP).",
     "(ninguna de datos)",
     "docs/html/fase6/m01_interpretabilidad_shap.html",
     "Indice de navegacion de los 4 submodulos SHAP."),
    ("f6_m01a_shap_global", "fase6",
     "Calcula importancia global SHAP y dependence plots (ganador, MLP, EBM); cachea valores SHAP.",
     "metricas_modelo.json; X_test_prep.parquet; y_test.parquet; models/<ganador>,MLP__none,EBM__none.pkl; caches results/fase6/*.pkl",
     "results/fase6/shap_global_ganador.pkl; shap_global_mlp.pkl; shap_importancia_comparativa.parquet; PNGs; HTML",
     "Interpretabilidad global comparativa; base SHAP reutilizada por m01b/c/d."),
    ("f6_m01b_shap_local", "fase6",
     "Genera explicaciones SHAP locales (waterfall, force, decision) por instancia.",
     "metricas_modelo.json; X_test_prep.parquet; y_test.parquet; models/<ganador>.pkl; results/fase6/shap_global_ganador.pkl",
     "results/fase6/perfiles_locales.parquet; PNGs; HTML",
     "Explicabilidad individual de casos concretos."),
    ("f6_m01c_shap_cohortes", "fase6",
     "Segmenta SHAP por titulacion, rama y grupos (cohortes) y genera heatmaps.",
     "metricas_modelo.json; X_test.parquet; X_test_prep.parquet; y_test.parquet; models/<ganador>.pkl; shap_global_ganador.pkl; df_exp_target_eda.parquet",
     "results/fase6/shap_cohortes_rama.parquet; shap_cohortes_titulacion.parquet; PNGs; HTML",
     "Analisis de interpretabilidad por subgrupos."),
    ("f6_m01d_shapash", "fase6",
     "Construye el dashboard interactivo de explicabilidad con Shapash.",
     "metricas_modelo.json; X_test_prep.parquet; y_test.parquet; shap_importancia_comparativa.parquet; models/<ganador>.pkl; shap_global_ganador.pkl",
     "results/fase6/shapash_dashboard.html; HTML (embebido)",
     "Dashboard interactivo de explicabilidad para revision y defensa."),
    ("f6_m02_interp_indice", "fase6",
     "Genera la pagina indice HTML del grupo M02 (interpretabilidad alternativa).",
     "(ninguna de datos)",
     "docs/html/fase6/m02_interpretabilidad_alternativa.html",
     "Indice de navegacion de LIME y DiCE."),
    ("f6_m02a_lime", "fase6",
     "Calcula explicaciones locales LIME y las compara con SHAP (consenso).",
     "metricas_modelo.json; X_test_prep.parquet; X_train_prep.parquet; y_test.parquet; perfiles_locales.parquet; shap importancia parquet; models/<ganador>.pkl",
     "results/fase6/lime_explicaciones.parquet; PNGs; HTML",
     "Interpretabilidad local alternativa y validacion cruzada con SHAP."),
    ("f6_m02b_dice", "fase6",
     "Genera contrafactuales accionables con DiCE (solo variables modificables) ordenados por coste.",
     "metricas_modelo.json; X_test_prep.parquet; X_train_prep.parquet; y_test.parquet; y_train.parquet; models/<ganador>.pkl",
     "results/fase6/<df_dice>.parquet; PNGs; HTML",
     "Recomendaciones accionables (que cambiar para reducir riesgo)."),
    ("f6_m03_fairness_indice", "fase6",
     "Genera la pagina indice HTML del grupo M03 (fairness y errores).",
     "(ninguna de datos)",
     "docs/html/fase6/m03_fairness_errores.html",
     "Indice de navegacion de Fairness y Errores FP/FN."),
    ("f6_m03a_fairness", "fase6",
     "Analiza equidad algoritmica (fairlearn) por variables sensibles, ROC por grupo e interseccion.",
     "metricas_modelo.json; X_test.parquet; X_test_prep.parquet; y_test.parquet; models/<ganador>.pkl; df_exp_target_eda.parquet",
     "results/fase6/fairness_metricas.parquet; fairness_interseccional.parquet; PNGs; HTML",
     "Evaluacion de equidad por grupos protegidos."),
    ("f6_m03b_errores_fpfn", "fase6",
     "Perfila falsos positivos y falsos negativos del modelo (patrones y costes, umbral 0.5).",
     "metricas_modelo.json; X_test.parquet; X_test_prep.parquet; y_test.parquet; models/<ganador>.pkl; df_exp_target_eda.parquet",
     "results/fase6/errores_fpfn.parquet; PNGs; HTML",
     "Diagnostico de los errores del modelo y sus perfiles."),
    ("f6_m04_robustez_indice", "fase6",
     "Genera la pagina indice HTML del grupo M04 (robustez/sostenibilidad).",
     "(ninguna de datos)",
     "docs/html/fase6/m04_robustez.html",
     "Indice de navegacion de Stress, Calibracion, Sostenibilidad y Robustez Temporal."),
    ("f6_m04a_stress", "fase6",
     "Evalua robustez ante perturbaciones (ruido, outliers, features ausentes) y mide degradacion.",
     "metricas_modelo.json; X_test_prep.parquet; y_test.parquet; models/<ganador>.pkl; shap importancia parquet",
     "results/fase6/stress_resultados.parquet; PNGs; HTML",
     "Pruebas de estres y robustez del modelo."),
    ("f6_m04b_calibracion", "fase6",
     "Evalua la calibracion de probabilidades (reliability, Brier, umbral optimo).",
     "metricas_modelo.json; X_test_prep.parquet; X_train_prep.parquet; y_test.parquet; y_train.parquet; models/<ganador>.pkl",
     "results/fase6/calibracion_metricas.parquet; PNGs; HTML",
     "Analisis de fiabilidad de las probabilidades y seleccion de umbral."),
    ("f6_m04c_sostenibilidad", "fase6",
     "Mide huella de carbono (codecarbon) y memoria del ganador frente a 2 modelos comparativos.",
     "metricas_modelo.json; X_test_prep.parquet; y_test.parquet; models/<ganador>,Stacking__balanced,EBM__none.pkl",
     "results/fase6/sostenibilidad_metricas.parquet; PNGs; HTML; emissions.csv (verificar)",
     "Analisis comparativo de sostenibilidad/eficiencia de modelos."),
    ("f6_m04d_robustez_temporal", "fase6",
     "Robustez temporal (AUC por cohorte 2010-2020), calibracion (ECE) y sostenibilidad operativa (Sec 4.8).",
     "metricas_modelo.json; models/<ganador>.pkl; pipeline_preprocesamiento.pkl; X_test_prep.parquet; meta_test_app.parquet",
     "data/06_interpretacion/robustez/auc_por_cohorte.parquet; data/06_interpretacion/robustez/metricas_{calibracion,sostenibilidad,robustez_temporal}.json; data/06_interpretacion/robustez/figuras/*.png; actualiza data/06_evaluacion/metricas_modelo.json; results/m04d_robustez_temporal_sec4_8.pdf; docs/html/fase6/m04d_robustez_temporal.html",
     "VIGENTE: genera cifras canonicas de la Sec 4.8 y anade bloque al JSON fuente. Es el unico de los dos (m04d/m05) en el orquestador f6_m00_ejecucion."),
    ("f6_m05_robustez_calibracion", "fase6",
     "DUPLICADO de m04d: mismas metricas de robustez temporal, calibracion y sostenibilidad (Sec 4.8).",
     "metricas_modelo.json; models/<ganador>.pkl; pipeline_preprocesamiento.pkl; X_test_prep.parquet; meta_test_app.parquet",
     "data/06_interpretacion/robustez/auc_por_cohorte.parquet (MISMOS ficheros que m04d); metricas_*.json; actualiza data/06_evaluacion/metricas_modelo.json; results/m05_robustez_calibracion_sec4_8.pdf; docs/html/fase6/m05_robustez_calibracion.html",
     "DUPLICADO NO orquestado (no esta en f6_m00_ejecucion). Escribe los mismos artefactos que m04d en data/06_interpretacion/robustez/. Su salida auc_por_cohorte.parquet la consume extraer_datos_ilustraciones_v3."),
    ("f6_m06_informe_final", "fase6",
     "Sintesis ejecutiva final: ganador, hallazgos, limitaciones y posicionamiento frente al estado del arte.",
     "metricas_modelo.json; X_test_prep.parquet; y_test.parquet; models/<ganador>.pkl; results/fase6/*.parquet + JSON de submodulos",
     "results/fase6/comparativa_estado_arte.parquet; PNGs; HTML",
     "Informe final agregado de la fase; cierre de la evaluacion e interpretabilidad."),
    ("modelos", "fase6",
     "Utilidad: inspecciona el ranking de modelos del maestro (top 10 por F1).",
     "data/05_modelado/results/resultados_maestro.parquet",
     "(ninguna)",
     "Consulta rapida del ranking y el ganador. HUERFANO (utilidad)."),
    ("shap_importancia_comparativa", "fase6",
     "Utilidad: inspecciona el parquet de importancia SHAP comparativa (shape, columnas, dtypes).",
     "results/fase6/shap_importancia_comparativa.parquet",
     "(ninguna)",
     "Verificacion del artefacto SHAP comparativo de m01a. HUERFANO (utilidad)."),
    ("verificacion_pre_m01a", "fase6",
     "Utilidad: verifica librerias y carga de los 3 .pkl (LightGBM, MLP, EBM) antes de m01a.",
     "metricas_modelo.json; X_test_prep.parquet; models/LightGBM__none,MLP__none,EBM__none.pkl",
     "(ninguna)",
     "Comprobacion previa de entorno y modelos. HUERFANO (utilidad)."),

    # ---------------- MISC / RAIZ / UTILS / DEFENSA / LINAJE ----------------
    ("explorar_titulaciones", "misc",
     "Construye un inventario de titulaciones agrupando df_alumno y lo clasifica por plan de estudios.",
     "data/02_processed/df_alumno.parquet",
     "data/01_raw/titulaciones_inventario.xlsx",
     "Exploratorio del catalogo de titulaciones. HUERFANO (salida no consumida)."),
    ("extraer_datos_ilustraciones_v3", "misc",
     "Extrae datos de ilustraciones (SHAP top15, dicc. features, AUC por cohorte, calibracion) a JSON.",
     "pipeline_preprocesamiento.pkl; models/LightGBM__none.pkl; X_test_prep.parquet; y_test.parquet; X_test.parquet; meta_test.parquet; auc_por_cohorte.parquet",
     "output_para_claude/ilustracion_17_shap_top15.json; features_dict_legible.json; ilustracion_19_auc_cohorte.json; ilustracion_20_calibracion.json",
     "Datos numericos reales para ilustraciones de la memoria. HUERFANO (terminal)."),
    ("energy_consumed", "misc(defensa)",
     "Lee el CSV de emisiones y muestra el CO2eq medido.",
     "data/06_evaluacion/sostenibilidad_defensa/emissions.csv",
     "(ninguna) - imprime emissions (kg CO2eq)",
     "Consulta rapida de la huella de carbono (defensa). HUERFANO (utilidad)."),
    ("sostenibilidad_defensa", "misc(defensa)",
     "Reentrena el pipeline ganador midiendo consumo con CodeCarbon (sin sobrescribir modelo/metricas).",
     "models/LightGBM__none.pkl; X_train_prep.parquet; y_train.parquet",
     "data/06_evaluacion/sostenibilidad_defensa/emissions.csv",
     "Medicion real de huella de carbono para la defensa. HUERFANO (terminal)."),
    ("f1_linaje", "misc(linaje)",
     "Genera el linaje de datos de Fase 1 con src/linaje (descubre parquet con glob).",
     "data/01_interim/*.parquet; data/02_processed/df_alumno_base.parquet; df_alumno.parquet",
     "docs/html/linaje/f1_linaje.html; data/demo/linaje/f1_linaje.{json,md,xlsx}",
     "Documenta la trazabilidad/linaje de datos de Fase 1 (web descargable). HUERFANO (terminal)."),
    ("leer_parquet", "misc(utils)",
     "Utilidad simple para abrir e inspeccionar cualquier .parquet cambiando una variable RUTA.",
     "por defecto data/06_evaluacion/meta_test_app.parquet (RUTA editable)",
     "(ninguna) - muestra el DataFrame",
     "Inspeccion de parquets intermedios durante el desarrollo. HUERFANO (utilidad)."),
    ("verificar_df_alumno", "misc(utils)",
     "Verificacion rapida del dataset df_alumno detectando su ruta automaticamente.",
     "data/02_processed/df_alumno.parquet",
     "(ninguna) - verificacion por pantalla",
     "Comprobacion de integridad del DataFrame de alumnado. HUERFANO (utilidad)."),
]

# Clasificacion de HUERFANOS (notebooks cuya salida nadie consume en el pipeline).
#   A-utilidad  : utilidad/diagnostico (solo imprime o verifica, sin artefacto de pipeline)
#   B-terminal  : produce un entregable final/lateral que ningun otro notebook consume
#   C-duplicado : duplica a otro notebook vigente
HUERFANOS = {
    # A) utilidades / diagnostico
    "leer_parquet": "A-utilidad", "verificar_df_alumno": "A-utilidad",
    "columnas_parquet": "A-utilidad", "ver_entornos": "A-utilidad",
    "comproba_parquet_2": "A-utilidad", "comprobar_existe_parquet": "A-utilidad",
    "fautoml_setup_entornos": "A-utilidad", "modelos": "A-utilidad",
    "shap_importancia_comparativa": "A-utilidad", "verificacion_pre_m01a": "A-utilidad",
    "plantilla_fX_m0Y": "A-utilidad",
    # B) terminales / laterales
    "explorar_titulaciones": "B-terminal", "extraer_datos_ilustraciones_v3": "B-terminal",
    "f1_linaje": "B-terminal", "energy_consumed": "B-terminal",
    "sostenibilidad_defensa": "B-terminal", "f0_actualizar_resumen": "B-terminal",
    # C) duplicado
    "f6_m05_robustez_calibracion": "C-duplicado",
}
MOTIVO = {
    "A-utilidad": "Utilidad/diagnostico: no produce artefactos del pipeline (solo imprime o verifica).",
    "B-terminal": "Produce un entregable final/lateral que ningun otro notebook consume.",
    "C-duplicado": "Duplica a f6_m04d_robustez_temporal (vigente); no esta en el orquestador.",
}

cols = ["notebook", "fase", "que_hace", "entradas", "salidas", "uso"]
df = pd.DataFrame(ROWS, columns=cols)
df["huerfano"] = df["notebook"].map(HUERFANOS).fillna("")

# Tabla resumen de huerfanos (para la hoja dedicada)
huf = df[df["huerfano"] != ""][["notebook", "fase", "huerfano"]].copy()
huf["categoria"] = huf["huerfano"].map({"A-utilidad": "A · utilidad/diagnostico",
                                        "B-terminal": "B · terminal/lateral",
                                        "C-duplicado": "C · duplicado"})
huf["motivo"] = huf["huerfano"].map(MOTIVO)
huf = huf[["categoria", "notebook", "fase", "motivo"]].sort_values(["categoria", "notebook"])

from openpyxl.styles import Alignment, Font, PatternFill
head_fill = PatternFill("solid", fgColor="1F4E78")

out = Path(__file__).parent / "inventario_notebooks.xlsx"
with pd.ExcelWriter(out, engine="openpyxl") as xw:
    df.to_excel(xw, index=False, sheet_name="inventario")
    ws = xw.sheets["inventario"]
    anchos = {"A": 32, "B": 16, "C": 60, "D": 60, "E": 70, "F": 60, "G": 14}
    for col, w in anchos.items():
        ws.column_dimensions[col].width = w
    for c in ws[1]:
        c.font = Font(bold=True, color="FFFFFF")
        c.fill = head_fill
        c.alignment = Alignment(vertical="center", horizontal="center")
    for row in ws.iter_rows(min_row=2):
        for c in row:
            c.alignment = Alignment(vertical="top", wrap_text=True)
    ws.freeze_panes = "A2"

    huf.to_excel(xw, index=False, sheet_name="huerfanos")
    ws2 = xw.sheets["huerfanos"]
    for col, w in {"A": 26, "B": 34, "C": 16, "D": 70}.items():
        ws2.column_dimensions[col].width = w
    for c in ws2[1]:
        c.font = Font(bold=True, color="FFFFFF")
        c.fill = head_fill
        c.alignment = Alignment(vertical="center", horizontal="center")
    for row in ws2.iter_rows(min_row=2):
        for c in row:
            c.alignment = Alignment(vertical="top", wrap_text=True)
    ws2.freeze_panes = "A2"

print(f"OK -> {out}  ({len(df)} notebooks, {len(huf)} huerfanos)")
print(df["fase"].value_counts().to_string())
print("\nHuerfanos por categoria:")
print(huf["categoria"].value_counts().to_string())
